language: java
jdk:
  - openjdk14
addons:
  apt:
    packages:
      - fakeroot
      - rpm
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - "MAVEN_OPTS=-Xmx3072m -XX:MaxPermSize=512m -XX:+CMSClassUnloadingEnabled -XX:-UseGCOverheadLimit"
before_install:
  - export JPACKAGE_HOME=$JAVA_HOME
  - echo "MAVEN_OPTS='-Xmx3072m -XX:MaxPermSize=512m'" > ~/.mavenrc

